// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _2026_SoulLucy_backend.Data;

#nullable disable

namespace _2026_SoulLucy_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_2026_SoulLucy_backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("_2026_SoulLucy_backend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Facilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            Facilities = "AC, Whiteboard, Proyektor, Wi-Fi",
                            Name = "Ruang Kelas A",
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 120,
                            Facilities = "AC, Sound System, Proyektor, Wi-Fi",
                            Name = "Ruang Kelas B",
                            Status = "Available"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            Facilities = "30 unit PC, AC, LAN, Proyektor",
                            Name = "Computer Laboratorium",
                            Status = "In Use"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 50,
                            Facilities = "Dolby Atmos, Recliner Seats, Peredam Suara",
                            Name = "Mini Theater",
                            Status = "Available"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 200,
                            Facilities = "Grand Stage, Sound System, Kapasitas Besar, AC",
                            Name = "Auditorium",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("_2026_SoulLucy_backend.Models.Booking", b =>
                {
                    b.HasOne("_2026_SoulLucy_backend.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
